### ISSUE TITLE
Errors in using package

### ISSUE THREAD

**Issue by juanchon998** [AguaClara-Reach/aguaclara#102]
Hello team (@oliver-leung ?)

I'm trying to see if I can use the new LFOM code in python to generate an LFOM design instead of using the Mathcad. I am trying to modernize!

However I am running into problems that are presumably associated with the import. I can't seem to import any packages:

![image](https://user-images.githubusercontent.com/27255695/47375244-141e0c80-d6ad-11e8-872e-e3fb62f1cbbe.png)

I have version 0.0.14 of the aguaclara package installed. I have just now installed and updated it using `pip uninstall aguaclara` and `pip install aguaclara`. I still could not get imports to work, so I went to where the package files are stored locally and `pip install .`-ed.
![image](https://user-images.githubusercontent.com/27255695/47375389-619a7980-d6ad-11e8-8630-278c659441aa.png)

I have python version 3.6.5
![image](https://user-images.githubusercontent.com/27255695/47375498-a45c5180-d6ad-11e8-8ac6-158b93013824.png)

Is there something simple I'm missing?
Thanks in advance

**Comment by fletchapin** [comment]
@juanchon998 I ran into almost the same problem last week when I was debugging the test cases. I don't think it's a bug with the package but how you're calling the import statement and where the kernel exactly is being run from. 

With that being said unfortunately I don't have an immediate answer for you on how to fix this since it's very dependent on your environment. When I just did `pip install -e .` from the top level of the master branch and then tried the import statement you showed it worked.

The only advice I have is to make sure to restart your kernel before testing the import statement because the kernel takes the state of the packages when it's created and is not dynamically updated. So for example if you reinstall the package after the kernel has been started the kernel will NOT change accordingly. If this issue persists let me know and I can try to schedule some time to debug for your machine/environment specifically.

**Comment by juanchon998** [comment]
Thanks for the help Fletcher! How do I restart my kernel? Is that what `pip install -e .` does?

I'll try it tomorrow and report back

**Comment by fletchapin** [comment]
Do `CMD + SHIFT + P` on Mac or `CTRL + SHIFT + P` on Windows in Atom then search `Restart` and Hydrogen’s command should appear. 

Restarting Atom will also restart the kernels since Atom kills them when it closes.

**Comment by fletchapin** [comment]
`pip install -e .` installs the package at the current directory rather than the latest pip version. That way you can use the latest updates pushed to master even if they haven’t been released on pip yet

**Comment by juanchon998** [comment]
I tried uninstalling the aguaclara package and reinstalling it with `pip install -e .` , then I restarted atom, restarted the kernel, and got the same error. I also get this error message whenever I open atom, which might have something to do with it.

![image](https://user-images.githubusercontent.com/27255695/47435164-3e310680-d761-11e8-81b5-2c150ecbc40f.png)

**Comment by oliver-leung** [comment]
Hey @juanchon998 , were you able to resolve this error? [Here is an issue](https://github.com/lgeiger/ide-python/issues/34) for the Atom Python plugin that talks about the same error that you're getting.

Did you try running `python -m pip install 'python-language-server[all]'`, and if so, what was the result?

**Comment by juanchon998** [comment]
Thanks for following up Oliver- I checked the issue you sent and did as mzannoni suggested. I ran `pip3 install --user --upgrade python-language-server[all]` and got a lot of "Requirement already satisfied" text _and_:
![image](https://user-images.githubusercontent.com/27255695/47967020-7caaa900-e01e-11e8-9ce4-1cdef15ba792.png)

So I added that path to my PATH

![image](https://user-images.githubusercontent.com/27255695/47967030-b67baf80-e01e-11e8-8c42-17bcb8d2bcba.png)


But to no avail, alas 😢 

When I run `python -m pip install 'python-language-server[all]'` I get this buncha red text:

![image](https://user-images.githubusercontent.com/27255695/47967037-d317e780-e01e-11e8-89df-e2fd1a28e54e.png)

**Comment by oliver-leung** [comment]
`python -m pip install 'python-language-server[all]` looks like it's getting a string parse error. The first line indicates that it's doubling the single quotes.

Perhaps try running

```
python -m pip install python-language-server
```

or

```
python -m pip install python-language-server[all]
```
or those commands without `python -m` at the beginning.

**Comment by oliver-leung** [comment]
Closing this as it hasn't been responded to in a while. @juanchon998 , please reopen this if necessary!
