### ISSUE TITLE
We don't know what 'opt.L_sed' is.

### ISSUE THREAD

**Issue by aaronyaosmith** [AguaClara-Reach/aguaclara#104]
aguaclara.design.floc contains the function 'a_ent_tank()' which uses the constant 'opt.L_sed'. However, 'opt' refers to 'aguaclara.core.optional_inputs' which has been deleted during our refactor. Additionally, looking at the history, 'L_sed' was never a part of 'aguaclara.core.optional_inputs'.

Until we figure out what 'L_sed' actually is (the sed tank has multiple lengths associated with it; which one is it?), we've replaced it with a placeholder constant with the value 1 meter.

**Comment by aaronyaosmith** [comment]
Here's the code context:
`while (A_ratio) > 1.01 and (A_ET_PV/A_new) < 0.99:
            A_ET_PV = A_new

            vol_floc = vol_floc(q_plant, hl, Gt, T)
            A_floc_PV = vol_floc/(depth_end + hl/2)
            A_ETF_PV = A_ET_PV + A_floc_PV

            W_min = width_floc_min(q_plant, hl, Gt, T, depth_end)

            W_tot = A_ETF_PV/opt.L_sed

            num_chan = num_channel(q_plant, hl, Gt, T, W_tot)
            W_chan = W_tot/num_chan

            A_new = opt.L_ET_max*W_chan

            A_ratio = A_new/A_ET_PV

        return A_new.to(u.m**2).magnitude`

**Comment by aaronyaosmith** [comment]
Here's the code context:
This is the body of a_ent_tank().

    while (A_ratio) > 1.01 and (A_ET_PV/A_new) < 0.99:
        A_ET_PV = A_new

        vol_floc = vol_floc(q_plant, hl, Gt, T)
        A_floc_PV = vol_floc/(depth_end + hl/2)
        A_ETF_PV = A_ET_PV + A_floc_PV

        W_min = width_floc_min(q_plant, hl, Gt, T, depth_end)

        W_tot = A_ETF_PV/opt.L_sed

        num_chan = num_channel(q_plant, hl, Gt, T, W_tot)
        W_chan = W_tot/num_chan

        A_new = opt.L_ET_max*W_chan

        A_ratio = A_new/A_ET_PV

    return A_new.to(u.m**2).magnitude

**Comment by fletchapin** [comment]
The value of L_Sed is 5.8 meters. I found it [here](https://github.com/AguaClara/aguaclara/commit/1e59a32bed61cd294519bca352623c8a9fb7cdbc#diff-b37defd42c059ea6235ace7a6bb52eb9R363) but it's found in a lot of the commit history.

Eventually L_Sed will be passed in from the sed tank which is designed first, so it should be an input into the class constructor (but use 5.8 m for testing)
