### ISSUE TITLE
Flocculator-sedimentation tank interactions

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#112]

**Comment by oliver-leung** [comment]
@monroews One discrepancy that we've run into is regarding the assumed length of the sedimentation tank when building the flocculator. The [textbook](https://aguaclara.github.io/Textbook/Flocculation/Floc_Design.html#specify) claims the sedimentation tank's maximum length should be 6m, but @fletchapin mentioned that he used 5.8m when he wrote design code. Does this 0.2m difference matter?

**Comment by monroews** [comment]
The maximum length is actually being set by the length of the inlet manifold pipe. The maximum length of pipes is 6 m. Thus that pipe with all of the diffusers can't be longer than 6 m. The total length of the sed tank will be significantly longer than 6 m because of the floc hopper. Thus the flocculator should be getting this length from Onshape.

**Comment by oliver-leung** [comment]
My bad, I meant to say that the *maximum length of the flocculator based on the length of the sedimentation tank length* was listed as 6m in the textbook. Does that quantity matter if it's 6m or 5.8m?

**Comment by monroews** [comment]
Both numbers are wrong. We need the real number from Onshape after the sedimentation tank is drawn.

**Comment by oliver-leung** [comment]
I see, we will take that into account and use Onshape's measurement feature for that.

**Comment by monroews** [comment]
We also have the goal of being able to design a stand alone flocculator based on the sizes given by a client.  Thus when a stand alone flocculator is created the length can be set by the engineer.

**Comment by oliver-leung** [comment]
I see, we'll pass in length when building the flocculator. I think we'll either use an Onshape measurement or make a sedimentation tank function to get that length, whichever is more stable. For now, we'll default the quantity to 6m until the sedimentation tank code is written.

**Comment by oliver-leung** [comment]
Might be needed for #150
