### ISSUE TITLE
metric drill series stops at 4.9 mm

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#136]
The metric drill series only includes tiny drills. This causes the LFOM function to fail when using metric drills. Add metric drill sizes up through about 5 cm. See McMaster perhaps for typical drill sizes.

def get_drill_bits_d_metric():
    """Return array of possible drill diameters in metric."""
    return np.arange(0.5, 5.0, 0.1) * u.mm

**Comment by fletchapin** [comment]
I've changed the range based on https://www.mcmaster.com/drill-bits to the following:

`np.concatenate((np.arange(1.0, 10.0, 0.1), np.arange(10.0, 18.0, 0.5),  np.arange(18.0, 36.0, 1.0))) * u.mm`

**Comment by monroews** [comment]
Please add some more all the way up to at least 5 cm. These are needed for design of the LFOM. They could even be in 10 mm intervals the rest of the way to 50 mm.

Thanks!!!!

**Comment by fletchapin** [comment]
Ok, I only stopped at 35 mm since that's where McMaster stopped in their catalog, but updated now
