### ISSUE TITLE
list handler wrapper missing from vertical orifice and horizontal orifice functions

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#137]
Vertical and horizontal orifice flow rates in physchem had a list_handler(HandlerResult="nparray"): wrapper that enabled them to handle arrays. That list handler is missing and because of that the functions can't handle arrays. This lost capability was needed for CEE 4520. I'm working on the design challenges for that course and am wondering if this capability can be restored or if there was a reason why this feature was not kept.

The list handler is in utilities.

**Comment by fletchapin** [comment]
@monroews This was removed when I found out ut.list_handler was breaking all our tests. Once I fixed the function I believe it should have been added back to all the functions, but this one was probably missed.

More details: https://github.com/AguaClara/aguaclara/issues/99

**Comment by fletchapin** [comment]
@oliver-leung I believe the function is fixed so the wrappers can be added back. Could you check that the tests pass when the wrapper is re-added to physchem?

**Comment by fletchapin** [comment]
I've gone ahead and added these back on my branch (fletch/miscFixes), but I didn't have time to test.

@monroews could you please test off this branch? I made a number of small changes and don't have the time to test them near thoroughly enough.

**Comment by monroews** [comment]
Perhaps @oliver-leung could test this. I won't have time this spring...
