### ISSUE TITLE
kinematic viscosity should be named kinematic viscosity, not nu

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#141]
Our naming convention uses the longer english names rather than the greek letters that are sometimes used. We use the english name convention for dynamic viscosity and for density. Thus we should stick with the english name convention for kinematic viscosity.

This needs to be reverted to the english convention in https://github.com/AguaClara/aguaclara/blob/master/aguaclara/core/physchem.py.

**Comment by monroews** [comment]
pc.viscosity_kinematic(Temperature) needs to be redefined asap! The fact that this function is missing is breaking lots of code!

**Comment by fletchapin** [comment]
I've updated this on my branch, but just wanted to confirm that we want to return to this name as we intentionally changed it in [this commit](https://github.com/AguaClara/aguaclara/commit/fbf2f79d0e5f4b6ac77d9058e1cbc95c04022194#diff-e9823cad2f53bb8c12cb1b56f464f64c).

**Comment by monroews** [comment]
It should revert to pc.viscosity_kinematic(Temperature) because that is the convention we are using for all other functions. We don't use the Greek symbols as function names.

**Comment by fletchapin** [comment]
Sure, in that case this is all set in my branch
