### ISSUE TITLE
K_MINOR_FLOC_BAFFLE missing from head loss code

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#144]
Our current estimate of the minor head loss coefficient (K_MINOR_FLOC_BAFFLE) for flow around the end of a 180 degree bend is
VC_BAFFLE_RATIO=con.VC_ORIFICE_RATIO**2
    K_MINOR_FLOC_BAFFLE = (1/VC_BAFFLE_RATIO - 1)**2

VC_BAFFLE_RATIO is our estimate of the flow contraction around a 180 degree bend.

**Comment by fletchapin** [comment]
@monroews I'm a little confused as to where you would want this defined. It seems to me that it's more complex than any of the other constants in head_loss.py, so I'm not sure if it should go there.

Also, I think it's already defined in line 96 of design/floc.py. Perhaps a comment should be updated to explain how that value was calculated? Once you let me know what you think is best I can add it to the fletch/miscFixes branch in which I made the other changes.

**Comment by monroews** [comment]
I suppose it should go with the other minor loss coefficients in head_loss.py.
Then the floc.py should pull it from head_loss.py.

**Comment by fletchapin** [comment]
Ok, this has been updated in fletch/miscFixes

**Comment by fletchapin** [comment]
So I've changed it, but while doing so I noticed that the equation you gave comes out to about 2.3, but the value used in the floc design code was 2.5, with a note: "Increased both to provide a safety margin on flocculator head loss and to simultaneously scale back on the actual collision potential we are trying to achieve."

Therefore, I'm wondering if this value should have been updated after all.

**Comment by monroews** [comment]
Hmmm... Okay, so the baffle minor loss coefficient is very sensitive to the value used for the orifice vena contracta coefficient. 

So set it to 2.5. Thanks for checking carefully!

**Comment by fletchapin** [comment]
Ok, I've updated this and created a PR. I'm closing these issues assuming the PR will be merged, but if there are any further issues they should be reopened.
