### ISSUE TITLE
Turbidity definition

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#145]
See https://github.com/AguaClara/aguaclara/blob/master/aguaclara/core/data/unit_definitions.txt

What should this conversion factor be? NTU = 1.7 * (mg / L)

After William provides the value, perhaps Oliver can update this.

**Comment by WPennock** [comment]
In Li et al. (2015), they found 68 NTU per 100 mg/L kaolinite, so we’ve used their ratio of 1.47 lately.

**Comment by fletchapin** [comment]
Updated in the same branch as the other changes (fletch/miscFixes)
