### ISSUE TITLE
release version out of sync with PyPi

### ISSUE THREAD

**Issue by fletchapin** [AguaClara-Reach/aguaclara#149]
Just noticed this when checking if my version incrementing worked when I changed the version in a new PR (#148).

Whenever students are back for this semester if you could take a look, and update the docs so they explain how to keep the versioning correct in the future, that would be great!

Screenshots to demonstrate the error, note how after v0.0.14 the histories diverge: 
![PyPi](https://user-images.githubusercontent.com/17417538/51360381-39d66a00-1a80-11e9-83ea-8c6641e763ee.png)
![Git Releases](https://user-images.githubusercontent.com/17417538/51360383-3cd15a80-1a80-11e9-950e-fa5c3b48f1ba.png)

**Comment by fletchapin** [comment]
P.S. My theory to how this happened was that the version was set to v0.0.16 and when I published the release originally without updating that version it overwrote the old v0.0.16 on PyPi, so I'll have to:

1) delete the current v0.0.17 release on git
2) tag the new PR as release v0.0.17 

The versioning for v0.0.17 should then be fixed. However, this won't fix the fact that v0.0.16 got overwritten on PyPi... Fixing that history is then what would be left to do (if we care enough about our version history). That'd be done by rolling back to the old v0.0.16 release tag on git and then manually trigger a PyPi release from that state.

**Comment by fletchapin** [comment]
@oliver-leung could you take a look a this?

I noticed on the 4520 class repo someone mentioned using an older version of the code (v0.0.16) to avoid a bug, but I'm afraid that they may not actually be using the version they think they are

**Comment by oliver-leung** [comment]
Fixed
