### ISSUE TITLE
list handler wrapper doesn't work for single values

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#151]
List handler is able to handle an array of one element, but can't handle a single element.

This works
density = pc.density_water(np.array([21])*u.degC)

This fails
density = pc.density_water(21*u.degC)

@oliver-leung @fletchapin 
This is causing problems in both courses, so fixing this is a high priority.

If needed a solution that can only handle a single value is better than the current version that can only handle arrays. Obviously, we'd like to have the ability to handle arrays or single elements!

**Comment by fletchapin** [comment]
@monroews I just checked and the density_water function doesn't use list_handler, so I don't believe it's an issue with that but instead is probably an issue with this line:
```rhointerpolated = interpolate.CubicSpline(WATER_DENSITY_TABLE[0], WATER_DENSITY_TABLE[1])```

To confirm this I ran ```radius_hydraulic(2*u.cm, 1*u.cm, False)``` (as you can see the inputs have no lists) and the function worked correctly.

If there are still issues with list_handler() please let me know. In the meantime I will try to get to the bottom of this issue (but don't think it's high priority as I believe it just affects list_handler)

**Comment by monroews** [comment]
There are TWO separate issues here and it doesn't seem that List handler is the issue in either case.

# problem with pint
I get an error running the pc.diam_pipe function when I am using pint version 0.9.
I can fix the error by installing pint version 0.8.1.
So for now I will recommend that students use pint version 0.8.1 until we can find out what is causing the error.
# problem with the density function
If you multiply the resulting value from the density function by 1 or do any other math on it before trying to display it, then it is fine. Thus I suspect that a quick fix would be to multiply the results by one when returning the value in the function. Not sure what the origin of the problem is.

**Comment by fletchapin** [comment]
@monroews understood. I'll let you know if I make any progress on those two issues, but I'm not sure how difficult it will be to find the root causes of these bugs

**Comment by oliver-leung** [comment]
The issue with `pint` has been resolved with #157 , and the issue with `pc.density_water` has been resolved with #173 .
