### ISSUE TITLE
Round significant figures with Pint units

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#153]
Some students in CEE 4520 are interested in rounding significant figures with the `ut.round_sf` function, but it doesn't play well with Pint units.

**Task:** Implement `ut.round_sf` so that it works with Pint units.

**Comment by fletchapin** [comment]
I added a commit which handles units in ```round_sf()``` in this branch: https://github.com/AguaClara/aguaclara/tree/fletch/list_handler

I'm not sure if it's the best way to do it but feel free to use it if it's helpful

**Comment by oliver-leung** [comment]
Thanks! I also added some test cases, could you approve #154 ?

**Comment by oliver-leung** [comment]
Completed
