### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by WalterGuardado** [AguaClara-Reach/aguaclara#155]
@oliver-leung Is it possible that the list handler needs to be modified or removed?

FlowRate = 10 * u.L / u.s
    HeadLoss = 1500 * u.m - 1440 * u.m
    Length = 2.5 * u.km
    Temp = 30 * u.degC
    Nu = pc.viscosity_kinematic(Temp)
    PipeRough = 0.1 * u.mm
    KMinor = 0.5 + 1
    

    pc.diam_pipe(FlowRate, HeadLoss, Length, Nu, PipeRough, KMinor)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-c6cabd7ac43d> in <module>
----> 1 pc.diam_pipe(FlowRate, HeadLoss, Length, Nu, PipeRough, KMinor)

~\AppData\Local\Continuum\anaconda3.1\lib\site-packages\pint\registry_helpers.py in wrapper(*values, **kw)
    190             # In principle, the values are used as is
    191             # When then extract the magnitudes when needed.
--> 192             new_values, values_by_name = converter(ureg, values, strict)
    193 
    194             result = func(*new_values, **kw)

~\AppData\Local\Continuum\anaconda3.1\lib\site-packages\pint\registry_helpers.py in _converter(ureg, values, strict)
    117         for ndx in unit_args_ndx:
    118 
--> 119             if isinstance(values[ndx], ureg.Quantity):
    120                 new_values[ndx] = ureg._convert(values[ndx]._magnitude,
    121                                                 values[ndx]._units,

IndexError: list index out of range

**Comment by monroews** [comment]
I get an error running the pc.diam_pipe function when I am using pint version 0.9.
I can fix the error by installing pint version 0.8.1.
you can try this by typing this in Anaconda prompt
pip install pint==0.8.1

**Comment by jacqueline-wong** [comment]
It works for me now! Thank you so much!

**Comment by oliver-leung** [comment]
Got it - let's continue discussion of the water density function in #152.

**Task**: specify `pint==0.8.1` in `setup.py`.

**Comment by oliver-leung** [comment]
Completed
