### ISSUE TITLE
New features for procoda_parser.py

### ISSUE THREAD

**Issue by HannahSi** [AguaClara-Reach/aguaclara#170]
`Get_data_by_time()` and `get_data_by_state()` should return NumPy arrays in place of lists to allow for vectorized operations, such as shifting every element of an array or taking a logarithm. The functions should also give an option for returning elapsed time in hours instead of day fraction.

**Comment by HannahSi** [comment]
We should have a function in procoda_parser for estimating the intersection of two sets (lists) of data. The following implementation worked for Ram Pump; it is based on finding the difference in the two data sets, detecting the two indices on either side of a sign change, and linearly interpolating the two data sets to find the intersection:

```python
def intersect(x, y1, y2):
    x_points = np.array([])
    y_points = np.array([])
    crossings = (np.argwhere(np.diff(np.sign(y1-y2)))+1).flatten()

    for c in crossings:
      slope1 = (y1[c] - y1[c-1]) / (x[c] - x[c-1])
      slope2 = (y2[c] - y2[c-1]) / (x[c] - x[c-1])
      b1 = y1[c] - slope1 * x[c]
      b2 = y2[c] - slope2 * x[c]
    
      x_points = np.append(x_points, (b2-b1)/(slope1-slope2))
      y_points = np.append(y_points, slope1*(b2-b1)/(slope1-slope2) + b1)
      
    return x_points, y_points, crossings
```

**Comment by alicezha0** [comment]
We need to input this functionality into procoda_parser. After inputting this method, we need to test it out and document it.

**Comment by ariannacurillo** [comment]
Hello @monroews,
We have two question in regards to implementing an intersection function that we would like your opinion on!

1) Would it be best to have two separate functions: one that assumes two lines have the same x coordinates and can therefore return the array indexes in which the intersections occur, and the other allowing a separate list of x coordinates for each line?

2) Should we consider intersections when the lines do not have any sign changes but still intersect? For example a parabola and a line tangent to the vertex of the parabola.
<img width="300" alt="Screen Shot 2020-09-19 at 11 47 14 AM" src="https://user-images.githubusercontent.com/56367876/93671077-08d8e480-fa6e-11ea-97bd-493efa22b213.png">

**Comment by monroews** [comment]
Good day,

Given that ProCoDA is collecting all of this data it will have the same
data interval and time stamps.
The big challenge is handling data that is noisy. I wouldn't worry about
the exact intersection case because that won't occur with noisy data.

Monroe Weber-Shirk | he/him/his

Phone: +1 (607) 216-8445  | monroews@gmail.com  |

**Comment by ariannacurillo** [comment]
Thank you for getting back to us @monroews !
We forgot to mention that two lines could also intersect without a sign change if they are equal, which could happen if both lines have hit an instrument's limit of detection (e.g. 0, 1000 NTU). Do you think it would worth giving an option to the user to include or exclude zero-sign change intersections?

**Comment by monroews** [comment]
Either way is fine. I don't think that the intersection without crossing will be a case that users will need. Note that if the instruments are out of range that the data isn't very useful in any case.

**Comment by HannahSi** [comment]
That is a good point. Thank you for your advice, Monroe!

**Comment by ariannacurillo** [comment]
I have finished implementing and testing the intersection function, and pushed code under my branch asc327/procode_parser.py that has these updates, but some tests cases are failing in the travis CI and appveyor checks.
