### ISSUE TITLE
max and min functions for NumPy arrays and Pint quantities

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#185]
Please answer each of these questions so that we know what to implement!

**Is your feature request related to a problem?**

There is a lot of repeated code when we want to find the maximum or minimum of multiple values that are either in a NumPy array or assigned units through Pint. The process involves stripping the units from the values, using Python's built-in `max()` function, then reassigning values to it.

**What kind of a solution would you like?**

There should be functions called `max` and `min` defined in `utility.py` that take in some indeterminate number of arguments (with units) and returns their maximum or minimum with units attached.

**Comment by sc2267** [comment]
Currently being worked on in #186
