### ISSUE TITLE
Wrong units on air density in constants.py

### ISSUE THREAD

**Issue by cheertsang** [AguaClara-Reach/aguaclara#191]
@HannahSi The AIR_DENSITY constant in [constants.py](https://github.com/AguaClara/aguaclara/blob/master/aguaclara/core/constants.py) should be 1.225 kg/m**3 (it's currently in kg/mm**3). 

However, Monroe proposes that air density should NOT be a constant! It should be calculated from PV=nRT. Perhaps making it a function of temperature and pressure would be more useful?

**Comment by oliver-leung** [comment]
Hey @cheertsang , thanks for bringing this to our attention!

It definitely makes sense to have density as a function. I suggest that we make AIR_M (air's molar mass) and R constants in physchem.py, then make the density function (in the form of d = PM/RT) which takes in T and P as parameters. AIR_M would be a default parameter, which could be changed if the user wanted to. Are there any other options that we should consider?

**Comment by HannahSi** [comment]
Thanks @cheertsang for making this issue! I agree with Oliver's suggestion for the air density function. Cheer and @monroews, is this the pressure- and temperature-dependent function you're looking for?

**Comment by monroews** [comment]
R is already a constant in units. We should be careful not to redefine universal constants that have already been defined.

Yes! This is the function we want.

**Comment by HannahSi** [comment]
Got it, thank you for the heads up and the confirmation! I'll add this in a new release of aguaclara.

**Comment by elenapertsalis** [comment]
For now we are relying on .to function to check for correct units (for pressure) but we're trying to see if there's a way we can allow any unit that is a unit of pressure.

**Comment by HannahSi** [comment]
This change will be released soon in version 24 (see the v0.0.24 branch of this repo)!

**Comment by HannahSi** [comment]
It turns out we removed the AIR_DENSITY constant in the last release but forgot to include our air_density function! @elenapertsalis is working on adding this to the next release.

**Comment by elenapertsalis** [comment]
We reopened this issue because we forgot to add the function to the previous release but I've added everything that's necessary including the function, the test cases and the documentation. The files include physchem.py and test_physchem.py.

**Comment by HannahSi** [comment]
The tests did not have the correct units nor the right values for the expected outputs. They have been fixed in the last commit of branch v0.1.0.
