### ISSUE TITLE
Peclet number calculation is always returned as 5.0. This is for Monroe's CEE 4530 class.

### ISSUE THREAD

**Issue by klr227** [AguaClara-Reach/aguaclara#192]
Please answer each of these questions so that we can resolve the bug!

**What were you trying to do?**
I am working on the Reactor Analysis lab and am trying to run the code that Monroe has placed on the wiki page. https://github.com/monroews/CEE4530/blob/master/Examples/reactor.md.  I am specifically working with my Advection Dispersion Model and the problem is that I always get a Peclet number of 5.

Steps I took.
E.g.
1. Open Atom...
2. Run Hydrogen on the line `from aguaclara.play import *`
3. Run All

**What was supposed to happen?**

I am supposed to get the same Peclet number as Monroe. We are using the same code and data. Both Monroe and I don't understand why we are getting different values for the same code.

**What actually happened?**
![Screen Shot 2019-03-18 at 5 08 18 PM](https://user-images.githubusercontent.com/31329564/54564173-7e5b8480-49a1-11e9-828f-949e267fb011.png)

- Operating system: macOS Mojave(Windows 10, macOS X, etc.)
- Python version: 3.7.1 
    
- .`aguaclara` version: 0.0.23
   
- Hydrogen version: 2.8.0

**Comment by oliver-leung** [comment]
What was the Peclet number that @monroews got?

**Comment by monroews** [comment]
I get The model estimate of the Peclet number was 3.464130166627788
We are running the exact same code. We are using the same version of aguaclara (23).

**Comment by elenapertsalis** [comment]
We fixed the units on air density!

**Comment by HannahSi** [comment]
Resolved by running code in terminal's Python shell instead of Atom's (unclear what the Atom bug was).
