### ISSUE TITLE
Unitless number in floc_model.gamma_coag

### ISSUE THREAD

**Issue by HannahSi** [AguaClara-Reach/aguaclara#200]
@WPennock brought to our attention that with the new addition of units to the materials in `aguaclara.research.floc_model.py`, the `gamma_coag()` function in `floc_model` no longer works. This seems to be because the call to `frac_vol_floc_initial()` uses a unitless 0 instead of 0*u.kg/u.m**3.

@elenapertsalis Can you add these units in the function and write tests to make sure it works with new release?

**Comment by elenapertsalis** [comment]
I fixed this issue by adding the proper units to the unitless 0.

**Comment by elenapertsalis** [comment]
I just have to finalize the test cases for this function.

**Comment by HannahSi** [comment]
We'll be discarding our changes because Will found a lower level cause and solution to the problem: the `u.wraps()` wrapper functions preceding our functions are meant to 
* take inputs of a certain dimension (e.g. `u.s` implies time)
* coerce them to the correct magnitude if the units are not as expected (e.g. `1 u.hr` --> `60 u.s`)
* remove the units and execute the function with unitless numbers
* apply the output units at the end (e.g. `u.g/u.m**3` if the function outputs concentration)

This causes a lot of problems with functions involving our `floc_model.Material` and`floc_model.Chemical` objects, such as applying units on top of other units, so we'll be removing the wrapper functions altogether.

**This fix will be in version 25 of the AguaClara package!**
