### ISSUE TITLE
Wrong directory separator for Windows OS in procoda_parser.py

### ISSUE THREAD

**Issue by HannahSi** [AguaClara-Reach/aguaclara#203]
In `aguaclara.research.procoda_parser`, `os.path.sep` is used to create a file path of the ProCoDA data log from the directory of the file and the name of the data log:
```python
if path[-1] != os.path.sep:
        path += os.path.sep

if not isinstance(dates, list):
        dates = [dates]

data = []
for d in dates:
        filepath = path + 'datalog ' + d + '.xls'
```

However, not only has `os.path.sep` given the wrong path separator on a Windows computer, but we should be using `os.path.join()`:

```python
for d in dates:
        filepath = os.path.join(path,  'datalog ' + d + '.xls')
```

This is more intuitive and should resolve differences in path separators.

**Comment by elenapertsalis** [comment]
The old code didn't fail on my laptop but we think the changes we've made will fix the problem for other people.
