### ISSUE TITLE
Removing outdated constants from aguaclara.core.constants

### ISSUE THREAD

**Issue by HannahSi** [AguaClara-Reach/aguaclara#206]
The following constants will be removed from `aguaclara.core.constants`:
* GRAVITY : this is included in the units package as `u.gravity`
* WATER_DENSITY : `aguaclara.core.physchem` has a function, `density_water(temp)`, for looking this up by temperature
* WATER_NU : `aguaclara.core.physchem` has a function, `viscosity_kinematic(temp)`, for calculating this by temperature
* ATM_P : this is `u.atm`
* AIR_NU : this should be a function based on pressure and temperature (TODO)
* LFP_FLOW_MAX : unused
* FITTING_S_MIN : unused
* CHANNEL_W_MIN : unused

@monroews I also found the unused constants:

```python 
#: The influence of viscosity on mixing in jet reactors
JET_ROUND_RATIO = 0.08
#: An estimate for plane jet ratios in the flocculator and sed tank jet reverser
JET_PLANE_RATIO = 0.0124
```

Do you believe these would be useful to keep? If so, should their descriptions be more descriptive?

**Comment by monroews** [comment]
see [AguaClara textbook](https://aguaclara.github.io/Textbook/Rapid_Mix/RM_Derivations.html?highlight=plane%20jet).

These constants relate the maximum energy dissipation rate in a jet to the kinetic energy time required for the jet to travel a distance equal to the width or diameter of the jet. These isn't an easy concept to wrap my head around. This parameter is useful for calculating maximum velocity gradients in both mechanical and hydraulic flocculators.

**Comment by HannahSi** [comment]
@monroews Thank you for the reference! Just to clarify, by "kinetic energy time", do you mean kinetic energy per time required for the jet to travel such a distance? And out of curiosity, is this energy dissipation in the form of heat due to shear stress?

**Comment by monroews** [comment]
Sorry! I wrote this incorrectly. And you fixed it. Good work.

This mechanical energy is converted to heat due to shear stress.

**Comment by HannahSi** [comment]
That's alright, thank you for the clarification! I think I have a decent understanding of the jet ratios and energy dissipation in jets now.
