### ISSUE TITLE
Sedimentor Design Code

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#211]
This issue will keep track of our progress on writing design code for the sedimentor (previously called the "sedimentation tank"), which will include the sedimentation tank and the sedimentation channel.

**Comment by oliver-leung** [comment]
@monroews Do you know what the H_{SedExitFree} variable marked in the photo is specifying? Could it be the freeboard?
![Annotation 2019-06-27 094857](https://user-images.githubusercontent.com/13292691/60271748-e7b43300-98c0-11e9-9760-03aadbc914a2.png)

**Comment by monroews** [comment]
Can you find the code for the function W.HorizChannel and find what it
requires for inputs?

Monroe Weber-Shirk | Senior Lecturer

Phone: +1 (607) 216-8445  | mw24@cornell.edu



AguaClara Cornell | Safe Water on Tap

Cornell University | 265 Hollister Hall | Ithaca, NY 14853 |
AguaClara.cornell.edu <http://aguaclara.cee.cornell.edu/>

<http://aguaclara.cornell.edu/>

**Comment by oliver-leung** [comment]
1. Flow
2. Depth (`HW.SedWeirExit - *H.SedExitFree*` goes into this) 
3. Head loss
4. Length
5. Kinematic Viscosity
6. Pipe roughness (or porosity? It's asking for an epsilon)
7. 1 if manifold
8. Minor loss coefficient

**Comment by monroews** [comment]
This is the upstream depth of water in the channel. The H.SedExitFree is
the vertical distance between the top of the weir that water is flowing
over into this channel and the maximum water level that we are willing to
have in this channel to ensure that there is no risk that the channel
starts influencing the water level in the sed tanks. I'd bet that
H.SedExitFree is either 5 or 10 cm.

Monroe Weber-Shirk | Senior Lecturer

Phone: +1 (607) 216-8445  | mw24@cornell.edu



AguaClara Cornell | Safe Water on Tap

Cornell University | 265 Hollister Hall | Ithaca, NY 14853 |
AguaClara.cornell.edu <http://aguaclara.cee.cornell.edu/>

<http://aguaclara.cornell.edu/>

**Comment by oliver-leung** [comment]
@monroews The equations for the sed. tank's outlet manifold are very complex and involve upwards of 20 new functions just to calculate the length and number of orifices. Are there any values that we can assume, like the length being around 6m?

**Comment by monroews** [comment]
The goal is to separate the geometric constraints from the hydraulic constraints. I'm guessing most of those equations are about geometry. Is the sed tank length an expert input? If so, that sets the length of the outlet manifold. The exact length of the manifold isn't that important because wall shear based head loss is not significant.

**Comment by oliver-leung** [comment]
Completed in #175
