### ISSUE TITLE
Verify component designs

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#215]
As per @monroews 's suggestion, a feature that we should be adding to the design code (coming from Mathcad) is the ability to verify designs in addition to the normal testing that we have implemented. This design verification would start from the finished object's calculated values, and run calculations on those finished values to ensure that the component would work as intended.

For example, there are equations for [checking the average velocity and residence time of the Flocculator](https://aguaclara.github.io/Textbook/Flocculation/Floc_Design.html#checking-the-flocculator-design).

We will need to make more decisions on how we would implement this, but I think a good way would be to make them as functions for each design class so that, once someone designs a component, they can immediately verify its design.

**Comment by Henry262799** [comment]
The design functions are deprecated
