### ISSUE TITLE
Water elevation calculations in design code

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#222]
**Is your feature request related to a problem?**

As proposed by @monroews, there is a need to track the elevation of water at each component within the class, both at the start and the finish. This is important for calculating the heights at which each component is built relative to the connecting geometry and concrete structure of the plant.

**What kind of a solution would you like?**

The solution would involve adding properties to each component design class that, using head loss and other calculations, would give the water elevation relative to some datum of the plant (likely the top/bottom row of LFOM orifices).

**What alternatives have you considered?**

One method of structuring the data that I considered was storing the change in elevation (Δz) from upstream to downstream of each component. Only a relative value is needed for isolated components.

When designing the entire plant, the `Plant` class would then be able to see all of its components' Δz's, and sum them with the plant datum's water elevation, allowing for correct placement of each component.

Monroe, please let us know if you have additional thoughts!

@ryan26192

**Comment by monroews** [comment]
This is exactly what we need. This feature will extend to connecting channels and pipes that are used to link processes. The connecting channels and pipes will be treated as an object that also has head loss and hence will be used by the plant class to set the heights of the upstream and downstream components. 
I assume this means that each component will have deltaz as an output and somehow a clear definition of what that delta z represents.

**Comment by oliver-leung** [comment]
Plant component design classes should be able to provide the head losses specified in [this discussion post](https://github.com/orgs/AguaClara/teams/aide-template/discussions/158).

**Comment by Henry262799** [comment]
The design functions are deprecated
