### ISSUE TITLE
Pipe/Pipeline design code (v2)

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#226]
Some suggestions that I've received for new pipeline design features:

- Account for losses when a valve is open
- Manifolds
- Ideal diameter when accounting for velocity/flow
- Reducers/expanders
- Creating pipelines from strings/arrays of strings for ease of use

These aren't entirely necessary for the current state of design code (minus manifolds), but can definitely be implemented in future versions.

**Comment by Henry262799** [comment]
The design functions are deprecated
