### ISSUE TITLE
Invalidate Flocculator design for degenerate cases

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#227]
As demonstrated by @monroews, it appears that the current `Flocculator` design code does not generate a constructible flocculator for `q > 180 * u.L / u.s`.

(TODO: insert graphs from Colab notebook)

This is because `end_water_depth` is no longer great enough to exceed the minimum H/S ratio required to flocculate properly. It was also demonstrated that, by increasing `end_water_depth`, we were able to attain higher `q`'s before running into a degenerate design.

There should be a check within the design code to warn the user of a degenerate design when the H/S ratio becomes too low. Furthermore, a future task would be to generate a horizontal flocculator design when a vertical flocculator can no longer be deep enough.

Note that this is similar to #215.

**Comment by Henry262799** [comment]
The design functions are deprecated
