### ISSUE TITLE
improvements to aguaclara/design/design_code_example.py

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#230]
Switch to the new import aguaclara as ac
Then you can write <class Monroe(ac.Component)>
I find the example difficult to follow. A simple realistic engineering example would be clearer.
like design a tank with a drain pipe.

**Comment by oliver-leung** [comment]
I've made a [revised design code example](https://github.com/AguaClara/aguaclara/blob/design_code_template/aguaclara/design/sed_example.py) that designs a minimal sedimentor (as well as its sedimentation tanks/channel). Let me know what you think!

**Comment by monroews** [comment]
Oliver,
This is a big improvement. 
Create an example with this that shows how you would use it and that doesn't return values of the parameters.
It would be great if this demonstrated setting the number of sed tanks based on a max length.  This would then illustrate how a component (sed tank) influences the sedimentor.

Yeah!

**Comment by Henry262799** [comment]
The design functions are deprecated
