### ISSUE TITLE
Entrance tank/flocculator hangs for flows between 55 and 60 L/s

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#231]
I was running my design challenge on flocculators for CEE 3520: safe water on tap.
I tried to design a 60 L/s entrance tank flocculator and the code hangs. I suspect that the code is switching back and forth between different numbers of channels and can't find a stable solution that includes an entrance tank. We might need to catch this error and force the number of channels to stay with the larger number even though that is a conservative design.
myfastetf = ac.EntTankFloc(q=60*u.L/u.s, floc = ac.Flocculator(gt=20000, temp=15 * u.degC, hl = 50 * u.cm))>

The code fails for flows between about 55 and 60 L/s.

**Comment by Henry262799** [comment]
The design functions are deprecated
