### ISSUE TITLE
Implement design code computation back-tracing

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#232]
One common pattern that I've seen within our design code logic:

1. Input a dimension guess
1. Run calculations using that guess
1. Output with a refined dimension

For example, sedimentor/sedimentation tank design language has the following logic - note the format of (inputs) => (outputs):

1. (inner tank width, inner tank length, ideal upflow velocity) => (ideal tank flow rate)
1. (ideal tank flow rate, plant flow rate) => (number of tanks)
1. (plant flow rate, number of tanks) => (actual tank flow rate, actual upflow velocity)

This pattern is not only pervasive, but also complex, making it a great candidate for abstraction! I propose that we make a feature addition to the `Component` class that allows the following functionality:

- Specify a guess/estimate/ideal for a component dimension
- Specify the calculations that use the g/e/i
- Go back and update the g/e/i for that dimension to be the actual dimension

**Comment by Henry262799** [comment]
The design functions are deprecated
