### ISSUE TITLE
Entrance tank requires trash rack

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#233]
The entrance tank needs additional length to accommodate 2 trash racks that are spaced at least 15 cm apart. We also need to ensure that there is space for the inlet pipe between the trash racks and the sloped flow barrier.

There must also be construction safety factors (space between drain pipe and wall, space between drain pipe and trash rack, space around LFOM).

**Comment by Henry262799** [comment]
The design functions are deprecated
