### ISSUE TITLE
Maximum Flow for vertical flow flocculators

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#237]
The maximum flow for a vertical flow flocculator is...

$$Q = \frac{W_{Max}H_e}{\Pi_{HS_{Min}} } \left( \frac{2 H_e  g^2 h_e^2}{K(G\theta)^2 \nu} \right)^\frac{1}{3}$$

![image](https://user-images.githubusercontent.com/28540907/63363863-6b7b2080-c342-11e9-816d-8253d1424060.png)

I get a max flow of about 180 L/s given our current design assumptions. The flocculator code should use this equation to set the maximum flow that it will create a design for. In the coming months we need to create the design algorithms and Onshape design for a horizontal flow flocculator

**Comment by Henry262799** [comment]
The design functions are deprecated
