### ISSUE TITLE
CDC revisions

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#238]
Units should not be stripped from numbers. This opens up the risk of unit errors.
CHange the coagulant viscosity equations to keep the units and to instead divide by the correct units. Thus the viscosity of PACl should be
`(1 + (2.383 * 10 ** -5) * ((ConcStock)/(u.kg/u.m**3)).to(u.dimensionless) ** 1.893) * ac.viscosity_kinematic(temp)`

Note that we force unit simplification before raising to an ugly power!

Expose the properties of viscosity and the maximum flow per dosing tube.

The maximum flow per tube needs to account for the (Reynolds number constraint)[https://aguaclara.github.io/Textbook/Flow_Control_and_Measurement/FCM_Derivations.html#equation-flow-control-and-measurement-fcm-derivations-41]. The Re constraint dominates for larger diameter tubes.  Without this constraint the code returns an invalid solution for large diameter dosing tubes. Fixing this is critical for high flow plants!

**Comment by Henry262799** [comment]
The design functions are deprecated
