### ISSUE TITLE
ac.round_sigs_figs doesn't show the required inputs

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#242]
I believe that the 
@optional_units([0], ['num'])
decorator above this function may be preventing it from correctly displaying what the required inputs are when you type the function in an IDE. I get "ac.round_sig_figs(*args, **kwargs)" when I type the parenthesis after the function name.

**Comment by Henry262799** [comment]
Is this still an issue? I just tried typing the function you specified and it showed me that we need to give a float that we wanted to apply sig figs to and the second argument is how many sig figs we wanted.

**Comment by Henry262799** [comment]
Fixed.
