### ISSUE TITLE
Flocculator Channel width constraint not met

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#246]
```
Floc = ac.Flocculator(q=120*u.L/u.s,temp=15*u.degC,ent_l=0*u.m, chan_n_parity='odd', l_max=7*u.m,)
print('Numero de canales',Floc.chan_n)
print('Ancho del canal',Floc.chan_w.to(u.inch))
print('Espacio entre pantallas',Floc.baffle_s)
```
I get a channel width of 44.88 inch even though the maximum width is 42 inches.

**Comment by monroews** [comment]
The algorithm also returns channels that are too narrow to be constructed. The minimum width criteria should always be met and if necessary the LENGTH of the channels should be reduced so that the width criteria can be met.

The parity criteria is also not always met. So the decision of which criteria to not follow is not being set correctly. I propose that the easiest criteria to not follow is the channel length. 

`parity='even'
Flows = np.array([10,100])*u.L/u.s
for myq in Flows:
  myfastetf = ac.EntTankFloc(q=myq, floc = ac.Flocculator(q=myq, gt=20000, temp=15 * u.degC, hl = 50 * u.cm,chan_n_parity=parity))
  print('Design flow rate ',myq)
  print('* Number of channels',myfastetf.floc.chan_n)
  print('* Channel width',myfastetf.floc.chan_w)
  print('* Channel length',myfastetf.floc.chan_l)
  print('* Baffle spacing',myfastetf.floc.baffle_s)
  print('* Number of obstacles',myfastetf.floc.obstacle_n.magnitude)
  print('* Entrance tank length',myfastetf.ent.l.to(u.m))
  print('* LFOM nominal diameter', myfastetf.lfom.pipe_nd)
  print('')`

Design flow rate  10 liter / second
* Number of channels 1
* Channel width 10 centimeter
* Channel length 6 meter
* Baffle spacing 28.7 centimeter
* Number of obstacles 1.0
* Entrance tank length 1.296 meter
* LFOM nominal diameter 6 inch

Design flow rate  100 liter / second
* Number of channels 2
* Channel width 46 centimeter
* Channel length 6 meter
* Baffle spacing 49.52 centimeter
* Number of obstacles 0.0
* Entrance tank length 1.782 meter
* LFOM nominal diameter 24 inch

**Comment by Henry262799** [comment]
The design functions are deprecated
