### ISSUE TITLE
Floc.serialize_properties() returns error

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#247]
`Floc = ac.Flocculator(q=120*u.L/u.s,temp=15*u.degC,ent_l=0*u.m, chan_n_parity='even', l_max=7*u.m,)`
`Floc.serialize_properties()`

When I use Floc.serialize_properties() to get all of the output from the design I get the following error.

> AttributeError: 'Pipe' object has no attribute 'onshape_config'

**Comment by Henry262799** [comment]
The design functions are deprecated
