### ISSUE TITLE
LFOM as subcomponent of ET returns the wrong pipe size

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#248]
I get two completely different answers depending on whether the LFOM is designed using the LFOM code or using the EntranceTank code.

`Train_q=40*u.L/u.s
w=42*u.inch
v_capture = 3*u.mm/u.s
temp= 20 * u.degC
ET=ac.EntranceTank(q=Train_q,plate_capture_vel=v_capture,floc_chan_w=w)
my_LFOM=ac.LFOM(q=Train_q,hl=20*u.cm)
print('LFOM ND',ET.lfom_nd)
print('LFOM ND',my_LFOM.pipe_nd)`

**Comment by monroews** [comment]
I'd suggest eliminating the multilevel design (Flocculator with Entrance tank with LFOM) in python and instead just make sure that we have great code for designing each individual component.

**Comment by Henry262799** [comment]
The design functions are deprecated
