### ISSUE TITLE
viscosity functions for coagulants should not be hidden

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#251]
The viscosity functions for PACl and Alum are given in cdc.py. Those functions are currently hidden. They should be public and the functions should explicitly include the temperature dependence.

**Comment by HannahSi** [comment]
@monroews Would this description (copied from cdc.py) suffice for explaining the temperature dependence?

> This function assumes that the temperature dependence can be explained
        based on the effect on water and that there is no confounding effect from
        the coagulant. 

@oliver-leung Is showing the functions just a matter of removing the underscores in front of `_alum_nu` and `_pacl_nu`? Also, should the CDC module be included in the package Sphinx documentation?

**Comment by oliver-leung** [comment]
Yup, you would just need to remove the underscores from the function names. I don't think they're truly hidden, though - adding an underscore to the front is just a convention to tell other programmers that they probably shouldn't use the function externally. More on that in [PEP 008](https://pep8.org/#descriptive-naming-styles).

If we want to make these functions public, I think we should keep CDC in the Sphinx docs (until/unless we move the functions to a different module).

**Comment by monroews** [comment]
The description is fine.

**Comment by HannahSi** [comment]
Thanks @monroews and @oliver-leung! 

I think the situation in Colab is in-between: functions beginning with underscores are hidden from autocompletions in Colab unless you actually type the underscore. As for Sphinx docs, CDC is not currently included, so I'll add it in.

**Comment by oliver-leung** [comment]
Ah I see - I wasn't aware of that feature!

**Comment by HannahSi** [comment]
Hi @monroews, I found two functions in `cdc.py` that seem to involve numbers of coagulant tubes. Would you know what the best description would be for each one?

```python
@property
def coag_tubes_active_n(self):
    coag_tubes_active_n = \
        np.ceil((self.coag_q_max / self._coag_tube_q_max).to_base_units())
    return coag_tubes_active_n

@property
def coag_tubes_n(self):
    coag_tubes_n = self.coag_tubes_active_n + 1
    return coag_tubes_n
```

**Comment by monroews** [comment]
there is always a spare tube for maintenance. active is what are in use. coag_tubes_n includes the spare.
