### ISSUE TITLE
Increase coverage in procoda_parser.py

### ISSUE THREAD

**Issue by HannahSi** [AguaClara-Reach/aguaclara#252]
`aguaclara.research.procoda_parser` currently has less than 80% coverage. Some of this is due to incomplete case analysis in`tests/research/test_ProCoDA_Parser.py`'s testing methods. For example, a function may be able to accept a string or an int for a certain parameter, but only the code dealing with an int is tested. We should add test cases so that the functions are completely covered. Coverage can be checked on [CodeCov](https://codecov.io/gh/AguaClara/aguaclara) (also linked in the repo README). 

There are also two methods, `plot_columns` and `iplot_columns`, that are untested because they produce Matplotlib plots. Pytests may not be appropriate for these functions, but we can try to test them using [Matplotlib's testing methods](https://matplotlib.org/3.1.1/devel/testing.html), specifically [check_figures_equal](https://matplotlib.org/3.1.1/api/testing_api.html#matplotlib.testing.decorators.check_figures_equal).

**Comment by alicezha0** [comment]
Added test cases for:
- column_of_data
- day_fraction
- time_column_index

**Comment by alicezha0** [comment]
Added test case for:
- data_from_dates

Fixed specifications for:
- column_start_to_end method in procoda_parser.py file

**Comment by alicezha0** [comment]
Added test case for:
- column_start_to_end

**Comment by alicezha0** [comment]
Added test cases for:
- plot_columns
- iplot_columns
which test figures

**Comment by alicezha0** [comment]
Need to figure out why the CI is failing with Appveyor

**Comment by alicezha0** [comment]
After adding option to change return unit (type time) in column_of_time, added test cases to test for new functionality

**Comment by alicezha0** [comment]
- Solved issue with CI failing with Appveyor through adding some import statements
- Work on procoda_parser continues with issue #253; pull request will occur after that issue is closed
