### ISSUE TITLE
ProCoDA parser

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#253]
I wanted to try ProCoDA parser to make sure I understood how it worked.
Here are the issues I encountered.

1) The format for the dates isn't clear. The documentation says "M-DD-YYYY". But the actual format appears to be [MM-DD-YYYY, MM-DD-YYYY]. Or maybe all of these options work???
2) I changed the data log to be tsv. I failed to convert the state log to tsv. I will make that change now!
3) I can't get it to load the data. I get a path or URL error. I replaced the back slashes with forward slashes, but the problem seems to be that it is using the wrong slash when it is assembling the path to the state log.

`path = 'https://github.com\monroews\playing\raw\master\ProCoDA_data'
dates = ["11-5-2019"]
state = 2
column = 2
mydata =ac.research.procoda_parser.get_data_by_state(path, dates, state, column, extension='.tsv')`

below is the error I get
---------------------------------------------------------------------------
InvalidURL                                Traceback (most recent call last)
<ipython-input-12-53d088cb78e8> in <module>()
      4 column = 2
      5 
----> 6 mydata =ac.research.procoda_parser.get_data_by_state(path, dates, state, column, extension='.tsv')

12 frames
/usr/lib/python3.6/http/client.py in putrequest(self, method, url, skip_host, skip_accept_encoding)
   1125         match = _contains_disallowed_url_pchar_re.search(url)
   1126         if match:
-> 1127             raise InvalidURL(f"URL can't contain control characters. {url!r} "
   1128                              f"(found at least {match.group()!r})")
   1129         request = '%s %s %s' % (method, url, self._http_vsn_str)

InvalidURL: URL can't contain control characters. '/statelog 11-5-2019.tsv' (found at least ' ')

I also tried ac.research.procoda_parser.column_of_data(path, start, column, end=None, units='').
Here is my code.
`path = 'https://github.com/monroews/playing/raw/master/ProCoDA_data/datalog 11-5-2019.tsv'

column = 2
start = 1
mycolumn = ac.research.procoda_parser.column_of_data(path, start, column, end=None, units='')`

I get the following error

---------------------------------------------------------------------------
InvalidURL                                Traceback (most recent call last)
<ipython-input-18-e9b2a955cbc4> in <module>()
      3 column = 2
      4 start = 1
----> 5 mycolumn = ac.research.procoda_parser.column_of_data(path, start, column, end=None, units='')

12 frames
/usr/lib/python3.6/http/client.py in putrequest(self, method, url, skip_host, skip_accept_encoding)
   1125         match = _contains_disallowed_url_pchar_re.search(url)
   1126         if match:
-> 1127             raise InvalidURL(f"URL can't contain control characters. {url!r} "
   1128                              f"(found at least {match.group()!r})")
   1129         request = '%s %s %s' % (method, url, self._http_vsn_str)

InvalidURL: URL can't contain control characters. '/monroews/playing/raw/master/ProCoDA_data/datalog 11-5-2019.tsv' (found at least ' ')

**Comment by monroews** [comment]
The problem appears to be the space in the file name. I've created a new executable for ProCoDA that replaces the space with _. That  change will require a change in any parser code that assembles file names from dates.

I couldn't find parser code to display the header of the data file. That would be a useful helper function.

Is there an example file showing how the ProCoDA parser can be used?

**Comment by monroews** [comment]
I was able to get 
`ac.research.procoda_parser.column_of_data(path, start, column, end=None, units='')`

to work correctly using a url to a file on github. I think the remaining issue is simple replacing the space with "_" when assembling data file names and state file names from dates.

**Comment by alicezha0** [comment]
For question 1:
- We wrote "M-D-YYYY" because for single digit months, there are no leading zeros. Is the single M misleading? Should we specify double MM?
- We are accepting both a single string date or an array of string dates. This is what we have for the specification for one of the functions:
    :param dates: A single date or list of dates, formatted "M-D-YYYY"
    :type dates: string or string list
Does this seem to be clear enough or should we add more detail?

**Comment by alicezha0** [comment]
To fix the path issue:
- get the path all the way to folder (raw)
- append the file name to the end of the url generated from before

**Comment by monroews** [comment]
I think I was confused about what was causing the file read errors. So I believe your date format is fine.

**Comment by alicezha0** [comment]
@monroews For the naming conventions of datalog and statelog files on the local computer, should they be in the style of urls, so they match? For example, should it be datalog_date.tsv vs what it is right now, which is datalog date.tsv?

**Comment by monroews** [comment]
The file naming convention for the latest release of ProCoDA is 
statelog_11-25-2019.tsv
datalog_11-25-2019.tsv
The student teams haven't installed this version of ProCoDA yet.

**Comment by HannahSi** [comment]
Currently, the `get_data_by_state` and `get_data_by_time` functions in `procoda_parser.py` can only accept folder paths that combine with filenames of the form "datalog_[date].tsv" or "statelog_[date].tsv" (and a slash in between, if necessary) to yield a real URL or local path. They should be updated to also accept "naive" Github URLs for the folder path by converting them to "intelligent" ones, which are already accepted by the functions. 

For example, for the file at https://github.com/AguaClara/aguaclara/blob/master/tests/research/data/Reactor_data.txt, 
* the full path of the raw file is https://raw.githubusercontent.com/AguaClara/aguaclara/master/tests/research/data/Reactor_data.txt,
* the naive path of the folder is https://github.com/AguaClara/aguaclara/blob/master/tests/research/data, and
* the intelligent path of the folder is https://raw.githubusercontent.com/AguaClara/aguaclara/master/tests/research/data

**Comment by HannahSi** [comment]
I just pushed code to the test-procoda-parser branch that resolves indexing bugs in `get_data_by_state`, as well as adds compatibility for "naive" github.com URLs! Next time, I'll add the few lines of code to `get_data_by_time` as well.

Before making a pull request, I'd also like to optimize the implementation for state-reading functions, such `get_data_by_state`, to use more of the efficient indexing methods available to Pandas series and dataframes. This will also help make the code more readable.

**Comment by HannahSi** [comment]
The function `read_state`, `average_state`, and `perform_function_on_state` have now been simplified to use `get_data_by_state`!

I realized `get_data_by_time` doesn't actually apply the units given in the arguments, so I'll be adding that functionality and an option for getting elapsed time (as opposed to real time of day) in the time column.

**Comment by HannahSi** [comment]
The elapsed time feature have been implemented and tested. The `test-procoda-parser` branch has been merged with the branch `asc327/procoda_parser.py`, which is addressing issue #170. Once the failing tests are resolved in that branch, we'll make a release with the combined updates to `procoda_parser`.
