### ISSUE TITLE
upgrade to newer matplotlib

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#255]
When we pip install aguaclara using colab we get the following errors.

We seem to be using an old version of matplot lib. Why not update that to the version used on colab?

Collecting aguaclara
  Downloading https://files.pythonhosted.org/packages/b3/b0/b8a7f63a63b37fb9259b344169ec380d0be193c12c3263dc50002e6a0724/aguaclara-0.1.13.tar.gz (85kB)
     |████████████████████████████████| 92kB 2.9MB/s 
Collecting matplotlib==3.0.3
  Downloading https://files.pythonhosted.org/packages/e9/69/f5e05f578585ed9935247be3788b374f90701296a70c8871bcd6d21edb00/matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0MB)
     |████████████████████████████████| 13.0MB 184kB/s 
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/dist-packages (from aguaclara) (1.24.3)
Collecting pint==0.8.1
  Downloading https://files.pythonhosted.org/packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz (162kB)
     |████████████████████████████████| 163kB 49.5MB/s 
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from aguaclara) (0.25.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from aguaclara) (1.3.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3->aguaclara) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3->aguaclara) (2.4.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3->aguaclara) (2.6.1)
Requirement already satisfied: numpy>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3->aguaclara) (1.17.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.0.3->aguaclara) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->aguaclara) (2018.9)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from kiwisolver>=1.0.1->matplotlib==3.0.3->aguaclara) (42.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.1->matplotlib==3.0.3->aguaclara) (1.12.0)
Building wheels for collected packages: aguaclara, pint
  Building wheel for aguaclara (setup.py) ... done
  Created wheel for aguaclara: filename=aguaclara-0.1.13-cp36-none-any.whl size=97010 sha256=592268f08a2a4953c459f0f97798f99e371ea877775509a10ef2d7222aa7d25b
  Stored in directory: /root/.cache/pip/wheels/13/65/3f/fa24d7d43535d7c44774b8f05d782324a26a155afc5447de05
  Building wheel for pint (setup.py) ... done
  Created wheel for pint: filename=Pint-0.8.1-py2.py3-none-any.whl size=134155 sha256=c2ae2b6b0db67b99ece59a2bf12486f4152ec448d0dd5f4d934c4eb19168cbc9
  Stored in directory: /root/.cache/pip/wheels/b4/56/36/7c4d6a4e3660e233b95e3b0482551915cb184abca0f93ee1dd
Successfully built aguaclara pint
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
Installing collected packages: matplotlib, pint, aguaclara
  Found existing installation: matplotlib 3.1.2
    Uninstalling matplotlib-3.1.2:
      Successfully uninstalled matplotlib-3.1.2
Successfully installed aguaclara-0.1.13 matplotlib-3.0.3 pint-0.8.1
WARNING: The following packages were previously imported in this runtime:
  [matplotlib,mpl_toolkits]
You must restart the runtime in order to use newly installed versions.

**Comment by HannahSi** [comment]
Resolved in release v0.1.16!
