### ISSUE TITLE
max dose of coagulant in cdc code is too high

### ISSUE THREAD

**Issue by jillfoley19** [AguaClara-Reach/aguaclara#256]
In the chemical dose controller code [CDC](https://github.com/AguaClara/aguaclara/blob/master/aguaclara/design/cdc.py), the max coagulant dose is currently 2 g/L which is too high for this system. The max dose should be set to 20 or 40 mg/L which would be more realistic. 

**What software are you using?**
macOS X Google Colab

**Comment by HannahSi** [comment]
This issue is being addressed in #258.
