### ISSUE TITLE
Adding in a Reynold's Number constraint to the CDC class code

### ISSUE THREAD

**Issue by jillfoley19** [AguaClara-Reach/aguaclara#257]
Please answer each of these questions so that we can resolve the bug!

**What were you trying to do?**
In the CDC class code, there is not a constraint for the Reynold's Number through the system. Because of this, the code is allowing for turbulent flows through the coagulant dosing tubes which violates the linear relationship between head loss and flow. 

We have come up with code that can be added to the CDC class code, specifically into the definition of the maximum flow through the coagulant tubes that would check the Reynold's number of the tubes. The code would set the maximum flow through the tube to always be laminar. The other properties for the coagulant tubes are set off of this value so this should solve the problem. 
 
`@property`
  `  def _coag_tube_q_max(self):`
       ` """The maximum permissible flow through a coagulant tube."""`
       ` coag_tube_q_max = ((np.pi * self.coag_tube_id ** 2)/4) * \`
            `np.sqrt((2 * self.error_ratio * self.hl * con.GRAVITY)/self.tube_k)`
        `re = pc.re_pipe(coag_tube_q_max,self.coag_tube_id,self._coag_nu)`
            `if re >= pc.RE_TRANSITION_PIPE`
              `coag_tube_q_max  = (pc.RE_TRANSITION_PIPE * np.pi * self.coag_tube_id* self._coag_nu)/4`
       ` return coag_tube_q_max`

**What software are you using?**
Python through Google Colab

**Is there anything else we should know?**

**Comment by Henry262799** [comment]
The design functions are deprecated
