### ISSUE TITLE
ac.ceil_nearest returns the smallest value when the largest value isn't large enough!

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#258]
This function should return an error if the value that is being rounded up is larger than the available range. It currently returns the smallest number in the array if the value that is being rounded up is larger than the largest value.

**Comment by HannahSi** [comment]
I'm rewriting `utility.ceil_nearest` and `utility.floor_nearest` to raise errors when the value is larger or smaller than the available range, respectively. The update causes the `cdc.coag_stock_vol` method to raise the `utility.ceil_nearest` error for a CDC object that uses the default CDC class properties. Here's some of the class:

```python
self.coag_dose_conc_max=2 * u.g / u.L #What should this default to? -Oliver L., 6 Jun 19
self.coag_stock_conc_est=150 * u.g / u.L
self.coag_stock_min_est_time=1 * u.day
...
self.chem_tank_dimensions_supplier=[
    [0.571, 0.851],
    [0.85, 0.99],
    [0.96, 1.10],
    [1.10, 1.02],
    [1.10, 1.39],
    [1.55, 1.65]
] * u.m
self.train_n=1

...

@property
def coag_q_max_est(self):
    coag_q_max_est = self.q * self.coag_dose_conc_max / \
        self.coag_stock_conc_est
    return coag_q_max_est

@property
def coag_stock_vol(self):
    coag_stock_vol = ut.ceil_nearest(
            self.coag_stock_min_est_time * self.train_n *
                self.coag_q_max_est,
            self.chem_tank_vol_supplier
        )
    return coag_stock_vol
``` 

@oliver-leung @ryan26192 Do you know what the difference is between `self.coag_dose_conc_max` and `self.coag_stock_conc_est`? @monroews would you know if there is a better (lower) default value for the former property?

**Comment by monroews** [comment]
self.coag_dose_conc_max  should be something like 100 mg/L

self.coag_stock_conc_est should be something like 150 g/L. 

Watch those units! There is a differenced of more than a factor of 1000.

**Comment by HannahSi** [comment]
Thanks Monroe! That makes much more sense. 

For documentation purposes, does `coag_q_max_est` return the estimated maximum permissible flow rate of the coagulant stock, whereas the method `coag_q_max` returns the actual maximum permissible flow rate of the coagulant stock? It looks like  `coag_q_max` uses a coagulant stock concentration that's based on the number of sacks of coagulant used.

**Comment by monroews** [comment]
Your descriptions of the variables are correct. _est is always used as a preliminary estimate in the design process. I don't think that we should be calculating the coagulant stock concentration based on the number of sacks of coagulant used. I think we should simply specify what we want the stock concentration to be. That would simplify this code.

**Comment by HannahSi** [comment]
Thanks for confirming. It looks like the method for calculating the number of coagulant sacks assumes plant operators use entire sacks at a time, not fractions of sacks. Do you think this is a reasonable assumption, or would it still be better for the user to define an exact coagulant stock concentration?

**Comment by monroews** [comment]
IT would be better for the user to define an exact stock concentration. We have to think of algorithms that will work over a wide range of plant flow rates and sacks won't  be a good unit for small plants.

**Comment by HannahSi** [comment]
Sounds good, thanks again for your input!
