### ISSUE TITLE
Sed tank inlet manifold design is incorrect

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#263]
The sed tank has this piece of code
`@property
    def diffuser_hl(self):
        """The headloss of the diffuser."""
        return self.inlet_man_hl / self.diffuser_n`

That is wrong on so many levels. The head loss through the diffusers does not get multiplied to get the total head loss. 

The head loss of the diffuser should be calculated based on the opening size of the port and the velocity that is thus leaving that port.

**Comment by Henry262799** [comment]
The design functions are deprecated
