### ISSUE TITLE
Replace Appveyor/Travis with GitHub Actions

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#265]
Currently, we use both Appveyor and Travis to test the package against Windows and macOS/Linux environments, respectively. However, due to the move to Google Colab, which I believe runs on Linux, I feel that it's no longer necessary to have to use both services for continuous integration.

Furthermore, with GitHub releasing their new Actions service, which has the ability to test against any number of operating systems and Python versions, I believe that it has the potential to replace Appveyor/Travis as a far more streamlined service.

We would want two separate workflows to:
- Run pytests for each push to a development (i.e. non-master) branch
- On merge with master, regenerate Sphinx documentation

[This](https://help.github.com/en/actions) is a great starting point for learning about Actions.

**Comment by HannahSi** [comment]
[peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) might be a helpful third party action for deploying Sphinx documentation! The readme provides pretty thorough documentation. A workflow is currently being tested on the `aguaclara_tutorial` repository.

UPDATE: [the workflow in `aguaclara_tutorial`](https://github.com/AguaClara/aguaclara_tutorial/blob/master/.github/workflows/generate-docs.yml) is now working!

**Comment by HannahSi** [comment]
The `pythonpackage.yml` workflow on the gh-actions branch now successfully runs Pytests on a push to any branch! Next steps are to transfer the rest of the commands in the `.travis.yml` to Github Actions workflows, including 
* running doctests
* running Codecov checks
* deploying tagged releases to PyPi
