### ISSUE TITLE
Design Check functions

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#278]
We would like functions that would take the dimensions from the Onshape design and calculate the expert inputs. For example, given the baffle spacing, depth, channel width, channel length, number of channels for the flocculator calculate the following.

- Gtheta
- G
- Head loss
- theta

This way we can prove that the Onshape design is in spec.
We'd want similar functions for each unit process.

**Comment by Henry262799** [comment]
The design function are deprecated
