### ISSUE TITLE
coag_tube_l throws a unit error instead of returning a length

### ISSUE THREAD

**Issue by fletchapin** [AguaClara-Reach/aguaclara#281]
Please answer each of these questions so that we can resolve the bug!

**What were you trying to do?**

```from aguaclara.design.cdc import CDC
cdc_obj = CDC(q = 20 * u.L/u.s, coag_type = 'pacl')
cdc_obj.coag_tube_l
```

**What was supposed to happen?**
I was using `aguaclara.design.cdc` to calculate the length of tube needed, but got a unit error when running the function.

**What actually happened?**
![image](https://user-images.githubusercontent.com/17417538/95613049-31268400-0a19-11eb-95fd-ff2489321978.png)

**What software are you using?**
Google Colab

**Comment by HannahSi** [comment]
Resolved in release 0.2.10!
