### ISSUE TITLE
error on running aguaclara.play import*

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#90]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
C:\Users\mw24\Anaconda3\lib\site-packages\pint\registry.py in load_definitions(self, file, is_resource)
    359                 else:
--> 360                     with open(file, encoding='utf-8') as fp:
    361                         return self.load_definitions(fp, is_resource)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mw24\\Anaconda3\\lib\\site-packages\\aguaclara\\core\\data/unit_definitions.txt'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-dcfecc321d47> in <module>()
----> 1 from aguaclara.play import*

C:\Users\mw24\Anaconda3\lib\site-packages\aguaclara\play.py in <module>()
     27 
     28 # Design imports
---> 29 from aguaclara.design.lfom import LFOM
     30 
     31 # Core imports

C:\Users\mw24\Anaconda3\lib\site-packages\aguaclara\design\lfom.py in <module>()
      1 """Build an Linear Flow Orifice Meter"""
----> 2 from aguaclara.core.units import unit_registry as u
      3 import aguaclara.core.constants as con
      4 import numpy as np
      5 import aguaclara.core.physchem as pc

C:\Users\mw24\Anaconda3\lib\site-packages\aguaclara\core\units.py in <module>()
     51     pd.options.display.float_format = ('{:,.' + str(n) + '}').format
     52 
---> 53 unit_registry.load_definitions(os.path.join(os.path.dirname(__file__), "data/unit_definitions.txt"))

C:\Users\mw24\Anaconda3\lib\site-packages\pint\registry.py in load_definitions(self, file, is_resource)
    366             except Exception as e:
    367                 msg = getattr(e, 'message', '') or str(e)
--> 368                 raise ValueError('While opening {0}\n{1}'.format(file, msg))
    369 
    370         ifile = SourceIterator(file)

ValueError: While opening C:\Users\mw24\Anaconda3\lib\site-packages\aguaclara\core\data/unit_definitions.txt
[Errno 2] No such file or directory: 'C:\\Users\\mw24\\Anaconda3\\lib\\site-packages\\aguaclara\\core\\data/unit_definitions.txt'

**Comment by eak24** [comment]
This should be fixed in 0.0.14. The issue was just that the data files weren't specified to be included in the package distribution. Please upgrade with `pip install aguaclara -U`
