### ISSUE TITLE
Where did cdc_functions.py, physchem.py, etc. go?

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#91]
A bunch of the code that was in aide_design seems to be completely gone. I've searched the whole AguaClara site and can't find it. This has resulted in several broken links in the textbook. @ethan92429

**Comment by eak24** [comment]
According to our plan, as dictated [here](https://github.com/orgs/AguaClara/teams/aguaclara-code) we have made a transition to a single "aguaClara" repository. physchem is in core, cdc_functions is in aguaclara. All research is in research folder, and all design functions are in the process of being migrated to the design subfolder. You can see all the filename changes I made [here](https://github.com/AguaClara/aguaclara/compare/2a8aa731657c284c027be6d04982b6c6b218546e...master). Does that help? In the future, if you want to make permanent links to a specific version, navigate to the version and then click "show files". That way we always link to something that actually exists!

**Comment by monroews** [comment]
I still can't find physchem.py anywhere.

**Comment by eak24** [comment]
https://github.com/AguaClara/aguaclara/blob/master/aguaclara/core/physchem.py
