### ISSUE TITLE
Kozeny equation is WRONG

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#95]
This function is in phys chem.

It incorrectly refers to PipeRough. That is wrong and is because I used epsilon for pipe roughness and for porosity in my notes. Replace PipeRough with Porosity in the equation below! To clarify, it just requires a change in the name of the variable.

@u.wraps(u.m, [u.m, u.m, u.m/u.s, u.m, u.m**2/u.s], False)
def headloss_kozeny(Length, Diam, Vel, PipeRough, Nu):
    """Return the Carmen Kozeny Sand Bed head loss."""
    #Checking input validity
    ut.check_range([Length, ">0", "Length"], [Diam, ">0", "Diam"],
                   [Vel, ">0", "Velocity"], [Nu, ">0", "Nu"],
                   [PipeRough, "0-1", "Pipe roughness"])
    return (K_KOZENY * Length * Nu
            / gravity.magnitude * (1-PipeRough)**2
            / PipeRough**3 * 36 * Vel
            / Diam ** 2)

**Comment by HannahSi** [comment]
The function has been corrected in branch "graphing" (which will become release 0.0.15).

```
@u.wraps(u.m, [u.m, u.m, u.m/u.s, u.m, u.m**2/u.s], False)
def headloss_kozeny(Length, Diam, Vel, Porosity, Nu):
    """Return the Carmen Kozeny Sand Bed head loss."""
    #Checking input validity
    ut.check_range([Length, ">0", "Length"], [Diam, ">0", "Diam"],
                   [Vel, ">0", "Velocity"], [Nu, ">0", "Nu"],
                   [Porosity, "0-1", "Porosity"])
    return (K_KOZENY * Length * Nu
            / gravity.magnitude * (1-Porosity)**2
            / Porosity**3 * 36 * Vel
            / Diam ** 2)
```
